services:
  - type: web
    name: google-phish
    env: python
    repo: https://github.com/GregUpload/Google.git
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true

